# WHU+ESCNet

lr: 0.001
num_epochs: 40
out_dir: escnet
criterion: WNLL+Cmpct
model: ESCNet

escnet_model:
  in_ch: 5
  out_ch: 20
  n_iters: 5
  n_spixels: 256
  n_filters: 32
  eta_pos: 2
  gamma_clr: 0.1
  offsets:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
lambda:
  - 0.5
  - 0.01
  - 0.1
merge_on: False