# Lebedev+DnD

model: DnD
out_dir: DnD
suffix_off: True

lambda_recon: 1.0
criterion: L1+WBCE
threshold: 0.5

num_workers: 4
crop_size: 224
lr: 0.0001
batch_size: 8
num_epochs: 15
track_intvl: 1
schedulers:
  - name: StepLR
    step_size: 5
    gamma: 0.5

dnd_arch: dnd
dnd_model:
  in_ch: 3
  out_ch: 1
  itm_ch: 128
  k: 32
  p: 1