# Lebedev+P2V

model: P2V
out_dir: P2V
suffix_off: True

k_train: 2
k_test: 2
criterion: WBCE
threshold: 0.5

num_workers: 4
crop_size: 224
lr: 0.0001
batch_size: 8
num_epochs: 15
track_intvl: 1
schedulers:
  - name: StepLR
    step_size: 5
    gamma: 0.5

p2v_model:
  in_ch: 3
  video_len: 8
  alpha: 0.5