# Lebedev+P2V

model: P2V
out_dir: P2V
suffix_off: True

criterion: WBCE
weights: 
  - 0.5   # Weight of no-change class
  - 0.5   # Weight of change class

threshold: 0.5

num_workers: 4
crop_size: 224
lr: 0.0004
batch_size: 8
num_epochs: 30
track_intvl: 1
schedulers:
  - name: StepLR
    step_size: 10
    gamma: 0.1

p2v_model:
  in_ch: 3
  video_len: 8