# Lebedev+CiDL

model: CiDL_Enc_Con+CiDL_Enc_Sty+CiDL_Dec+CiDL_Dis+CiDL_Dis
criterion: MSE+L1+L1+L1+CC
optimizer: Adam+Adam+Adam+Adam+Adam
out_dir: CiDL
suffix_off: True

lambda_adv: 1.0
lambda_vis: 10.0
lambda_lat: 1.0
lambda_self: 10.0
lambda_cross: 100.0
threshold: 0.5

dataset: Lebedev_CiDL
batch_size: 4
repeats: 1
crop_size: 256
num_epochs: 200
lr: 1.e-4
sched_on: False

cidl_model:
  enc_con:
    input_dim_a: 3
    input_dim_b: 3
  enc_sty:
    input_dim_a: 3
    input_dim_b: 3
    output_nc: 8
  dec:
    output_dim_a: 3
    output_dim_b: 3
    nz: 8
  dis:
    input_dim: 3
    norm: 'None'
    sn: False

_CiDL: True