# Basic configurations on LEVIR-CD dataset


# Data
dataset: LEVIR-CD
num_workers: 2
repeats: 2
subset: val
crop_size: 256


# Optimizer
optimizer: Adam
lr: 0.002
weight_decay: 0.0
load_optim: False
save_optim: False
sched_on: True
schedulers:
  - name: StepLR
    step_size: 30
    gamma: 0.2


# Training related
batch_size: 8
num_epochs: 100
resume: ''
anew: False
device: cuda


# Experiment
exp_dir: ../exp/
# tag: ''
# suffix: ''
# DO NOT specify exp_config
debug_on: False
inherit_off: False
log_off: False
track_intvl: 5
tb_on: False
tb_intvl: 1000
suffix_off: False
save_on: False
out_dir: ''


# Criterion
criterion: WNLL
weights: 
  - 0.5   # Weight of no-change class
  - 0.5   # Weight of change class


# Model
model: 