# LEVIRCD+ESCNet

lr: 0.004
schedulers:
  - name: StepLR
    step_size: 20
    gamma: 0.5
num_epochs: 80
out_dir: escnet
criterion: WNLL+Cmpct
model: ESCNet

escnet_model:
  arch: full
  in_ch: 5
  out_ch: 20
  n_iters: 5
  n_spixels: 256
  n_filters: 32
  alpha: 0.01
  eta_pos: 2
  gamma_clr: 0.1
  offsets:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
lambda:
  - 0.5
  - 0.01
  - 0.1
merge_on: False