# SVCD+ESCNet

schedulers:
  - name: StepLR
    step_size: 20
    gamma: 0.5
num_epochs: 50
out_dir: escnet
criterion: WNLL+Cmpct
weights:
- 0.4
- 0.6
model: ESCNet

escnet_model:
  arch: full
  in_ch: 5
  out_ch: 20
  n_iters: 5
  n_spixels: 256
  n_filters: 32
  alpha: 0.01
  eta_pos: 2.5
  gamma_clr: 0.25
  offsets:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
lambda:
  - 0.5
  - 1.e-4
  - 1.0
merge_on: False